### ISSUE TITLE
Missing .gitignore file

### ISSUE THREAD

**Issue by msampathkumar** [HydPy/HydPy-meetups#1]
Could please add a .gitignore file? It's a nice practice to ignore cache/Jupyter Notebook metadata. Also, check to clear cached ignored files data.
```
.ipynb_checkpoints
.pyc
```
Overall, thanks for sharing 👍

**Comment by chirag200666** [comment]
Fixed by commit https://github.com/HydPy/HydPy-meetups/commit/a14b509c5a38a5cca61872885c40774cb8ee058f
