### ISSUE TITLE
Python and Netflix

### ISSUE THREAD

**Issue by kalyan678** [HydPy/HydPy-meetups#10]
Title of the talk/workshop
Python and Netflix- What happens when you stream a film?

Abstract of the talk/workshop
The one-stop destination for every movie buff is, of course, Netflix. But what if you were watching your favorite movie and it keeps buffering every now and then? You would just shut down the application and choose another option. But, how does it manage the traffic of millions of users swiftly? Thanks, to PYTHON! Netflix use Python through the full content lifecycle, from deciding which content to fund all the way to operating the CDN that serves the final video to its users.

Outline
•	This internet entertainment giant is a huge proponent of Python, using the language primarily for data analysis and back end services. It allows their software engineers to choose what language to code in, and have noticed a large upsurge in the number of Python applications.
•	Quoting the Python developers at Netflix, “the language is used through the “full content lifecycle”, from security tools to its recommendation algorithms, and its proprietary content distribution network (CDN) Open Connect”.
•	Ranging from Administrative domains to Reliability and Data Science to Machine Learning etc., Netflix uses Python for nearly every edge of their business.

Duration (including Q&A)
30 to 45 minutes including Q&A 

Level of Audience
Everyone

Speaker Bio
1. Speaker: Kalyan Prasad- Self Taught Data Scientist. I am highly accomplished business professional with domain expert and have skilled in the areas of Machine learning and Deep learning using Python and R platforms.  My work includes executing data-driven solutions to increase efficiency, accuracy, and utility of internal data processing. Experienced at creating data regression models, using predictive data modelling, and analysing data mining algorithms to deliver insights and implement action-oriented solutions to complex business problems. I love discovering data trends, seeing unique correlations, and telling the stories behind the numbers from financial data in various forms.
2. Company: Thingmax
3. Email: kalyan.prsd@gmail.com
4. Years of Exp: 9.5
 
Prerequisites
•	Familiarity with Python
•	Basic understanding of Machine learning and Big data

**Comment by inovizz** [comment]
@kalyan678 - could you please add slides of this talk by coming weekend?

**Comment by kalyan678** [comment]
@inovizz  Yes! I'll do it by weekend.

**Comment by kalyan678** [comment]
[
[Python and Netflix_Meetup.pptx](https://github.com/HydPy/HydPy-meetups/files/4250556/Python.and.Netflix_Meetup.pptx)

**Comment by kalyan678** [comment]
> @inovizz Yes! I'll do it by weekend.

**Comment by kalyan678** [comment]
[Python and Netflix_Meetup.pptx](https://github.com/HydPy/HydPy-meetups/files/4250580/Python.and.Netflix_Meetup.pptx)
Done. Thanks!
