### ISSUE TITLE
2D to 3d Reconstruction

### ISSUE THREAD

**Issue by dhiyo** [HydPy/HydPy-meetups#11]
**Title of the talk/workshop**

**Abstract of the talk/workshop**

**Category of the talk/workshop**

**Duration (including Q&A)**

**Level of Audience**

**Speaker Bio**

**Prerequisites(if any)**

**Comment by inovizz** [comment]
@dhiyo - this is not a valid proposal unless you add all of these

Title of the talk/workshop

Abstract of the talk/workshop

Category of the talk/workshop

Duration (including Q&A)

Level of Audience

Speaker Bio

Prerequisites(if any)

**Comment by inovizz** [comment]
Please reopen the issue when you have above details. Thanks, I'm closing it for now.
