### ISSUE TITLE
Writing your own container in python

### ISSUE THREAD

**Issue by shubham1172** [HydPy/HydPy-meetups#12]
**Title of the talk/workshop**
Writing your own container in python

**Abstract of the talk/workshop**

> "What I cannot create, I do not understand" - Richard Feynman

Containers are ubiquitous. We use container software like Dockers and Linux Containers (LXCs) every day without knowing what goes inside that black box. In this talk, we will explore the principles of containerization and how it functions in the Linux ecosystem. We will build a mini container in Python on top of Linux. We will learn how modern containers function and how we can realize the same functionalities in our mini container.

**Category of the talk/workshop**
8. Developer tools and automation - Testing, CI/CD, **Containers**, Orchestration, Logging and Monitoring, Cloud, SRE

**Duration (including Q&A)**
25 minutes (20+5)

**Level of Audience**
Intermediate

**Speaker Bio**
I am a budding computer engineer in my senior year and I have been using Python for about 3 years. Computers have always fascinated me and so have the brilliant people who brought computers to where they are today. I have worked in various domains ranging from software development to machine learning.

* I am pursuing my undergraduate degree from Vellore Institute of Technology, Chennai
* Currently interning at Microsoft, India

mail: [shubhamsharma1172@gmail.com](mailto:shubhamsharma1172@gmail.com)

**Prerequisites(if any)**
Users should have some familiarity with containers and Linux.

**Comment by shubham1172** [comment]
[Here](https://docs.google.com/presentation/d/1o056shL2bAWqGYV14B2Kg2DABGFJs1YPJATtngj6J5w/edit?usp=sharing)'s the link to the rough presentation. I will be also doing a quick coding session at slide 5.

**Comment by inovizz** [comment]
Hi @shubham1172 - would you be able to finish up the slides by coming weekend?

**Comment by shubham1172** [comment]
Hey @inovizz, I guess it's final. I will be coding and referring Linux man pages more than showing the slides!

**Comment by shubham1172** [comment]
Link to the script I wrote during the talk - https://gist.github.com/shubham1172/7c53130e6e0258f998f331955564dc4c

**Comment by cskarthik22** [comment]
Can you please share the video link..

**Comment by shubham1172** [comment]
Hey, @cskarthik22, I don't have it yet. Will post the link when I get it.

**Comment by shubham1172** [comment]
@cskarthik22 it's available at https://www.youtube.com/watch?v=VThBhfnTRiY
