### ISSUE TITLE
Memory Management in Python - The Basics

### ISSUE THREAD

**Issue by GoelJatin** [HydPy/HydPy-meetups#13]
**Title of the talk/workshop**
Memory Management in Python - The Basics

**Abstract of the talk/workshop**
We'll be talking about how objects are stored in stored in memory and how they're garbage collected.
1. Reference count
1. Garbage collection
1. Generational garbage collection
1. Some gotchas
1. And then finally, some quick optimizations you can do in your Python code

**Category of the talk/workshop**
Core Python

**Duration (including Q&A)**
45 minutes

**Level of Audience**
Beginner / Intermediate

**Speaker Bio**

Jatin comes with a total of 4.5+ years of industry experience ranging from Tools and Automation, Cloud Services, REST APIs and right now Programmatic Advertising, where most part of the journey has been along the lines of **Core Python and Standard Library**
I am currently working with **Spiceworks** as Software Engineer II. You can find me on Twitter [@_JatinGoel](https://twitter.com/_JatinGoel)
**Email:** jatingoel1037@gmail.com

**Prerequisites(if any)**
Nothing specific, but having some basic knowledge of Python would be helpful.

**Comment by GoelJatin** [comment]
I'll share the slides soon.

**Comment by inovizz** [comment]
@GoelJatin - Would it be possible to reduce this to 30 mins?

**Comment by GoelJatin** [comment]
> @GoelJatin - Would it be possible to reduce this to 30 mins?

I'll see what I can do.

**Comment by inovizz** [comment]
Also, could you please add slides by coming weekend?
