### ISSUE TITLE
Improving Deep Neural Networks

### ISSUE THREAD

**Issue by rajulayek** [HydPy/HydPy-meetups#18]
**Title of the talk/workshop**
Improving Deep Neural Networks.

**Abstract of the talk/workshop**
This talk is about getting deep learning to work well. Rather than the deep learning process being a black box, it will help us understand what drives performance, and be able to more systematically get good results. It will also cover the basics of TensorFlow.

**Category of the talk/workshop**
Data Science, Machine Learning, and AI

**Duration (including Q&A)**
30 Mins

**Level of Audience**
Beginner

**Speaker Bio**

1. Speaker Bio (Brief) Raju Layak, Currently working as Software Developer at Verizon.
2. Company Verizon
3. Email raju.layak@verizon.com
4. Years of Exp 4.5

**Prerequisites(if any)**
No requirements.

**Comment by inovizz** [comment]
@rajulayek - can you confirm your availability on 21st meetup one more time?
