### ISSUE TITLE
Programming Microcontrollers using CircuitPython

### ISSUE THREAD

**Issue by iayanpahwa** [HydPy/HydPy-meetups#23]
**Title of the talk/workshop**
Programming Microcontrollers using CircuitPython

**Abstract of the talk/workshop**
Programming microcontrollers can be intimidating for beginners, especially when it includes setting up toolchain including cross-compilers, assemblers to flashing the code using special techniques and not to mention the bit twiddling it needs at register level to perform any function. As IoT becomes more mainstream and uC becomes more powerful it is made possible to program these constraint devices using our fav programming language like MicroPython and CircuitPython. In this talk I'll be talking about CircuitPython project, setting up n running and showcasing basic projects anyone can do with some knowledge of hardware and python to make makers projects 

**Category of the talk/workshop**
Embedded Python and IOT - MicroPython, Python on Hardware, Robotics, Arduino and Raspberry 

**Duration (including Q&A)**
40 mins

**Level of Audience**
Begineer

**Speaker Bio**
1. Speaker Bio (Brief) - https://codensolder.com/about
Embedded software engineer, FPV Drone Racing Pilot, Maker, Open source software and hardware promoter 
2. Company- Mentor Graphics, A Siemens Business
3. Email - iayanpahwa@gmail.com
4. Years of Exp - 5

**Comment by inovizz** [comment]
@GoelJatin  - can we schedule this in the month of May?

**Comment by GoelJatin** [comment]
Yes, I was thinking about it. May 23 the DSUG event is scheduled so I was thinking May 30th.

@iayanpahwa , are you available for 30th this month?

And can we extend the duration of the meetup to be 1 hour?

**Comment by iayanpahwa** [comment]
I am available on 30th, what time are we planning it for ?

**Comment by GoelJatin** [comment]
Hey @iayanpahwa , as discussed over mail, the meetup is scheduled for May 29, 17:00 - 18:00

https://meetup.com/HydPyGroup/events/270578783/
Meeting URL - https://meet.jit.si/HydPyMeetup-29/05/2020

@inovizz , can you please update the labels for this issue
