### ISSUE TITLE
Talk about Scala programming language and how it handles concurrency 

### ISSUE THREAD

**Issue by sanghisha145** [HydPy/HydPy-meetups#25]
**Title of the talk/workshop**

Scala Concurrency

**Abstract of the talk/workshop**

This talk is to provide session on scala as a programming language, why we need it and dive into 1 of its feature concurrency

**Category of the talk/workshop**

Others

**Duration (including Q&A)**

30min including 5min of Q/A

**Level of Audience**

Beginer

**Speaker Bio**

1. Speaker Bio (Brief)  -> Divya Sanghi is a senior software engineer who is interested in Big Data and processing, cloud computing, containerization, distributed systems, design system. 
2. Company/College -> Walmart Labs
3. Email                     -> divyasanghi145@gmail.com
4. Years of Exp           ->3

**Prerequisites(if any)**

**Comment by inovizz** [comment]
@sanghisha145 - would you like to present this talk in March? 

Also - could you please add more details in the talk abstract on what you'll be covering in 30 mins. Is it going to be an introduction to Scala and then you'll dive into concurrency feature.

Please also advise on what should be the pre-requisites of this talk.

**Comment by bpkapkar** [comment]
Hello @sanghisha145 ,

Thank you for submitting your talk proposal. As this is an old submission, we are closing this request. If you're still interested in giving an in-person talk in Hyderabad, feel free to reopen this request or submit a new one. We'll gladly review the details and consider it for our upcoming meetups.

Thank you for your understanding, and we look forward to your continued interest!
