### ISSUE TITLE
Customizing Django Admin Interface

### ISSUE THREAD

**Issue by bhansa** [HydPy/HydPy-meetups#30]
**Title of the talk/workshop**
Customizing Django Admin Interface

**Abstract of the talk/workshop**
Django admin is an integral part of any Django project development. There is constant need or ask to update 
the interface such as like adding extra columns, adding filters, making lists searchable and even overriding admin templates.

In this talk we will talk about:
 - Django Admin Interface
 - Adding attribute columns 
 - Customizing Django Admin login screen by overriding Django OOTB templates.

**Category of the talk/workshop**
Web

**Duration (including Q&A)**
40 mins

**Level of Audience**
Beginner/Intermediate

**Speaker Bio**
Bharat has 3.5+ years of experience working as a JavaScript and AEM Developer.
I have been exploring python frameworks by creating projects on Django, flask with angular and react.
I have experience with websites, plugins, automation scripts, performance analysis etc.
**Twitter**: https://twitter.com/@293bharat
**Email**: bsaraswat45@gmail.com

**Prerequisites(if any)**
You should have some knowledge of python and Django framework(https://www.djangoproject.com/).
To follow along with demo, you can have **pip** and **Django** installed on your system.

**Comment by ananyo2012** [comment]
Recording available at https://www.youtube.com/watch?v=tWSALWMv-uE
