### ISSUE TITLE
Regression Testing with Touca

### ISSUE THREAD

**Issue by ghorbanzade** [HydPy/HydPy-meetups#32]
Touca: A new way of testing complex software

**Abstract**
[Touca](https://touca.io), is an early stage startup building an automated regression testing system that helps engineering teams understand the true impact of their code changes on the behavior and performance of their software. [Here's](https://www.youtube.com/watch?v=0pI-GsyqXUg) a short video if you like to learn more about Touca. We just released our [Python SDK](https://github.com/trytouca/touca-python) which enables software engineers writing code in Python to use our platform. We'd like to showcase this SDK, explain how it works, and do a live demo of performing regression testing with Python using Touca.

**Category**
Developer tools and automation: Testing

**Duration (including Q&A)**
30 to 45 min (including Q&A)

**Level of Audience**
Everyone

**Speaker Bio**
Founder at Touca.io
Previously: Senior software engineer at Vital Images, a Canon Group company
Previously: Software engineer at VMware Carbon Black
Email: firstname@lastname.com
Experience: 5y

**Comment by GoelJatin** [comment]
Hi @ghorbanzade , thank you for your proposal. We'll review and get back to you for further updates.

cc: @inovizz @bhansa @kalyan678

**Comment by ghorbanzade** [comment]
Sounds good!

**Comment by bpkapkar** [comment]
Hello @ghorbanzade ,

Thank you for submitting your talk proposal. As this is an old submission, we are closing this request. If you're still interested in giving an in-person talk in Hyderabad, feel free to reopen this request or submit a new one. We'll gladly review the details and consider it for our upcoming meetups. We hope to see you at our upcoming meetups.

Thank you for your understanding, and we look forward to your continued interest!
