### ISSUE TITLE
Graphs as Matrices

### ISSUE THREAD

**Issue by BabneetRehal** [HydPy/HydPy-meetups#36]
**Title of the talk/workshop**
Graphs as Matrices

**Abstract of the talk/workshop**
Graphs and matrices go hand in hand. In this talk, i give an overview of this Graph Matrix duality and how it can used for defining efficient graph processing algorithms.

We'll also briefly look at the GraphBLAS initiative, an ongoing community effort that includes representatives from industry, academia, and government research labs.

The GraphBLAS initiative (launched in 2013) aims to define a standard to capture graph algorithms in the language of linear algebra - following the footsteps of the BLAS standard which, starting four decades ago, revolutionised scientific computing by defining constructs on dense matrices.

**Category of the talk/workshop**

**Duration (including Q&A)**
60 minutes

**Level of Audience**
All

**Speaker Bio**
[AJ Ross](https://www.linkedin.com/in/lasersox/) (CTO, Fluxon) & [Praveen Kumar Telugu](https://www.linkedin.com/in/praveen-telugu/) (Director of Engineering, Fluxon)

AJ's Bio :
AJ Ross is a pragmatic full-stack software engineering leader with a passion for solving challenging business problems. He is the CTO of Fluxon, a global product development firm with offices in the US, Canada, India and Ukraine. Prior to Fluxon, AJ spent 7 years at Google, leading engineering for Retail Operations as they entered the hardware market. He was a Founding Member of Google Customer Reliability Engineering team, spearheading the creation of a new role dedicated to ensuring reliability of customer systems on Google Cloud Platform. He also led production readiness reviews for Fortune 500 companies.

Praveen's Bio :
Praveen Telugu brings more than a decade of experience in leading engineering teams, building production quality software, and architecting distributed systems. Praveen was the founding engineer of Fluxon, and today he leads an engineering team and oversees client projects. He also serves on the board of Fluxon’s India operations. Previously, Praveen was a Software Engineer at Google, where he developed business intelligence and sales productivity tools. He brings a curious mind, motivational management style and lifelong passion for designing, coding and problem-solving to the team. In his spare time, Praveen loves reading books on History and Critical Theory and is an avid chess player.

Prerequisites - Sign up for Q&A session with the speakers at [Dory](https://dory.app/)

**Comment by ananyo2012** [comment]
@BabneetRehal Can you add the speaker name and link to his public profile ? Also when is the tentative date you are planning to host this session ?

**Comment by BabneetRehal** [comment]
@ananyo2012 I have added the names & their LI profile links. Also, we are looking to finalise the date as 14 July, 2022. 
Let me know if it shall be fine?

**Comment by BabneetRehal** [comment]
@MandakiniSatpathy24

**Comment by ananyo2012** [comment]
@BabneetRehal What is the tentative time you want to host the talk on 14th July ?

**Comment by BabneetRehal** [comment]
@ananyo2012 It shall be 07 pm IST.

**Comment by BabneetRehal** [comment]
@ananyo2012 I have updated the speaker's bio. Could you check this also. Thanks!

**Comment by ananyo2012** [comment]
@MandakiniSatpathy24 Let's go ahead with 14th July, 7 pm IST as discussed over call. Let us know which platform you want to host the event. We will need to add the call link to the meetup.

**Comment by MandakiniSatpathy24** [comment]
@ananyo2012 Thanks for confirming the date and time, sure we will keep you posted about the platform by EOD today or max by tomorrow morning.

**Comment by BabneetRehal** [comment]
Hey @ananyo2012 
I have sent an email with the image asset for talk along with the registration form link. Could you please check it once and let us know the next action?
Thanks!

**Comment by BabneetRehal** [comment]
@ananyo2012 - Updated pre-requisites. Please check once.
