### ISSUE TITLE
Deep dive into the Twitter API v2 in Python using Tweepy

### ISSUE THREAD

**Issue by sparack** [HydPy/HydPy-meetups#37]
**Title of the talk/workshop**
Deep dive into the Twitter API v2 in Python using Tweepy

**Abstract of the talk/workshop**
In this hands on workshop, developers will learn about the new Twitter API v2 and how to build apps with it using Flask and Tweepy in Python. This session is open to all devs. Before building the Flask app with 'login with Twitter' functionality, we will spend time writing basic code to get data from the Twitter API. We will also look at examples of apps built with the Twitter API and learn how other students and researchers use the Twitter API.

**Category of the talk/workshop**
Web development 

**Duration (including Q&A)**
90 minutes

**Level of Audience**
Beginner

**Speaker Bio**
[Suhem Parack](https://twitter.com/suhemparack) is a Staff Developer Advocate at Twitter and spends his time helping students, researchers and developers in their journey of using and developing with the Twitter API. Prior to joining Twitter, he was a Solutions Architect at Amazon.

**Prerequisites(if any)**
Please apply for access to the Twitter API v2 ahead of time, by visiting t.co/signup If you have any issues, please reach out [@suhemparack](https://twitter.com/suhemparack)

**Comment by bpkapkar** [comment]
Hello @sparack ,

Thank you for submitting your talk proposal. As this is an old submission, we are closing this request. If you're still interested in giving an in-person talk in Hyderabad, feel free to reopen this request or submit a new one. We'll gladly review the details and consider it for our upcoming meetups.

Thank you for your understanding, and we look forward to your continued interest!
