### ISSUE TITLE
Python: A Career Shaping Programming Language

### ISSUE THREAD

**Issue by indrag49** [HydPy/HydPy-meetups#41]
**Title of the talk/workshop**
Python: A Career-Shaping Programming Language

**Abstract of the talk/workshop**
Python is ubiquitous. If your day job is in any kind of scientific field, you might have had an encounter with Python, no matter how minuscule. For me, who is currently a mathematics Ph.D. student, Python has been a significant basis for my entire journey. This is more of a story than a talk. A story of how Python has been shaping my career trajectory since my undergraduate days, which started out with a major in Physics. 

I spent my undergraduate days pursuing a major in Physics. I had no formal exposure to Python and all I understood during my first year were "classical mechanics" and "laboratory practicals". It was during the semester break that year when I accidentally bumped into a gold mine, a beautiful pedagogical introduction to Python. This talk tells the story of this unexpected encounter, and how eventually it made me fall in love with Python. This talk tells the story of how my mindset totally changed surrounding what I envisioned to be when I finished my degrees. Obviously, it wasn't easy. The journey comes with a lot of hurdles. This is a story of how a programming language inculcated in me the courage to take the road not usually taken. I think I am making Robert Frost proud! 

The general issue that I plan to address through this talk is how in mainstream academia taking risks is not that simple. I somehow managed to take the leap of faith and Python has always been my anchor. I simply hope the audience can resonate with this story of mine.

The purpose of this talk is twofold: 
1. To convey that it is perfectly fine to break free and pursue whatever career one is comfortable with. Python made me realize my goals. 
2. To give an overview of how I, a mathematics Ph.D. student, have been using Python for several projects ever since.

**Category of the talk/workshop**
Career; Scientific Computation in Mathematics

**Duration (including Q&A)**
40 mins (30mins + 10 mins)

**Level of Audience**
Beginner

**Speaker Bio**
1. I am a Ph.D. candidate in applied mathematics from the School of Mathematical and Computational Sciences, Massey University. I work on dynamical systems and chaos. Besides my research topic, I am also interested in computational physics, optimization, data analysis, open-source software development, etc. I write codes in Python and R, and sometimes Fortran. For more, have a look at my [website](https://indrag49.github.io/).
2. Institute: Massey University, Palmerston North, New Zealand
3. Email: indranilg49@gmail.com
4. Years of Exp: Final year doctorate; Dabbling in Python for the last 6 years

**Prerequisites(if any)**
NA

**Note**
If possible I want to deliver my presentation (remote) in March.

**Comment by bpkapkar** [comment]
Thank you @indrag49 for submitting your proposal. We have thoroughly reviewed the proposal and after careful consideration, we have decided to proceed with your proposal and look forward to discussing the next steps.

The upcoming HydPy meet-up is an offline meet-up in Hyderabad. Please let us know your availability for this talk on February 25, 2023, so we can plan further steps accordingly. The talk will last approximately 45 minutes, including a Q&A session. @inovizz

**Comment by indrag49** [comment]
Hello @bpkapkar , thank you for your message.  Yes Feb 25, 2023, works for me. But, I live in New Zealand now. Is there any chance I could present online?

**Comment by indrag49** [comment]
Hello @bpkapkar, thanks for letting me know. I appreciate it.

**Comment by bpkapkar** [comment]
Hello @indrag49 ,

Thank you for submitting your talk proposal. Since we're currently focusing on in-person meetups, we are closing this request for now. If we plan any online events in the future, we will reach out to you. Alternatively, if you're in Hyderabad and interested in presenting in person, please let us know, and we would be happy to consider it.

Thank you for your understanding, and we look forward to staying in touch!
