### ISSUE TITLE
modern observability with opentelemetry python

### ISSUE THREAD

**Issue by srikanthccv** [HydPy/HydPy-meetups#42]
**Title of the talk/workshop**

modern observability with opentelemetry python

**Abstract of the talk/workshop**

In this talk, I want to introduce people to the new observability/monitoring standard rapidly emerging in the cloud native space. OpenTelemetry is the second most popular project under the CNCF foundation. It enables one to instrument and collect information that can be extremely powerful for debugging issues. Its auto instrumentation gets you up and running quickly with rich traces, metrics, and, optionally, logs with a correlation b/w them. Overall, this will be about the value it provides and can potentially make people to revisit their monitoring strategies.

**Category of the talk/workshop**

Developer tools and automation (Monitoring, Logging, and Tracing)

**Duration (including Q&A)**

45 min.

**Level of Audience**

Intermediate to Advance

**Speaker Bio**

1. I am a software engineer based out of hyderabad. Avid open source enthusiast and Pythonista. I am one of the maintainers of the [opentelemetry-python](https://github.com/open-telemetry/opentelemetry-python). I like cycling and endurance sports in general.
2. SigNoz (https://signoz.io)
3. srikanth.chekuri92@gmail.com
4. 4 years

**Prerequisites(if any)**

Can I carry my Mac machine so I can set it up for some demo?

**Comment by bpkapkar** [comment]
Thank you @srikanthccv for submitting your proposal. We have thoroughly reviewed the proposal and after careful consideration, we have decided to proceed with your proposal and look forward to discussing the next steps.

The upcoming HydPy meet-up is an offline meet-up in Hyderabad. Please let us know your availability for this talk on February 25, 2023, so we can plan further steps accordingly. The talk will last approximately 45 minutes, including a Q&A session.

**Comment by srikanthccv** [comment]
I will be available in person.

**Comment by bpkapkar** [comment]
We are writing to request for brief summary about a you @srikanthccv  and have a photo of you to share with audience attending the talk. Would it be possible for you to provide requested information and allowing to use the same. Thank you for your time and consideration. We look forward to hearing back from you soon.

**Comment by srikanthccv** [comment]
photo:
<img width="191" alt="Screenshot 2023-02-10 at 4 58 04 PM" src="https://user-images.githubusercontent.com/22846633/218114255-ebfbd4e3-d192-4bed-b278-453176f6330b.png">

brief summary:

I am a software engineer with a wide range of interests, including programming languages, databases, observability and web techonologies. I work at SigNoz, an open source observability platform. I am an avid open source enthusiast and help maintain the OpenTelemetry Python. Outside work, I like cycling, running, and music.

**Comment by bpkapkar** [comment]
I wanted to reach out to you to kindly request that you submit the speaker’s consent form for our upcoming talks. The form can be found at https://forms.gle/xK2CtTcrpUAoNU2YA .

It’s great to have you as a speaker at our event, and your participation would be greatly appreciated. If you have any questions or concerns, please don't hesitate to contact us.

Check out this Meetup with Hyderabad Python User Group: https://meetu.ps/e/LSCGS/M7kcz/i for the event that you can share with your contacts and community that might be interested to join.

Also, I would like to invite you to follow us on LinkedIn for further updates and news about our group: https://www.linkedin.com/company/hyderabad-python-users-group/.

Thank you @srikanthccv  for your time and consideration.
