### ISSUE TITLE
Automated Test Framework using Python

### ISSUE THREAD

**Issue by heyswati06** [HydPy/HydPy-meetups#43]
**Automate the complete Test Execution for your Python project**

**A Test Automation framework is a constructive blend of various guidelines, coding standards, concepts, processes, practices, project hierarchies, modularity, reporting mechanism, test data injections etc to pillar automation testing. This talk will cover the starting point of architecting our own test automation framework by identifying the various components, putting all blocks together and discussing few use case implementations.**

**Test Automation**

**30 mins**

**Intermediate**

**Senior Software Engg with more than a decade of experience, currently working with Morgan Stanley**

**Prerequisites(if any)**

**Comment by bpkapkar** [comment]
Thank you @heyswati06  for submitting your proposal. We have thoroughly reviewed the proposal and after careful consideration, we have decided to proceed with your proposal and look forward to discussing the next steps.

The upcoming HydPy meet-up is an offline meet-up in Hyderabad. Please let us know your availability for this talk on February 25, 2023, so we can plan further steps accordingly. The talk will last approximately 45 minutes, including a Q&A session. @inovizz

**Comment by bpkapkar** [comment]
We are writing to request for brief summary about a you and have a photo of you to share with audience attending the talk. Would it be possible for you to provide requested information and allowing to use the same. Thank you for your time and consideration. We look forward to hearing back from you soon.

**Comment by heyswati06** [comment]
Hi Team,

Please find my basic bio below and photo attached-

" Swati is a highly experienced software Lead developer with over 10 years
in IT. She has a proven track record of delivering innovative solutions
across various industries, including Storage & Infrastructure Automation,
Analytics, Virtualization, Telecom, and Life Sciences. In addition to her
technical expertise, Swati actively participates in diverse activities such
as expos, DevOps/SRE events, intern sessions, and global forums. She also
takes an interest in mentoring interns and supporting recruitment efforts.
Swati is excited to be part of this community and connect with like-minded
individuals."

Thanks and Regards,
Swati
(+91-9717238784)

**Comment by bpkapkar** [comment]
I wanted to reach out to you to kindly request that you submit the speaker’s consent form for our upcoming talks. The form can be found at https://forms.gle/xK2CtTcrpUAoNU2YA .

It’s great to have you as a speaker at our event, and your participation would be greatly appreciated. If you have any questions or concerns, please don't hesitate to contact us.

Check out this Meetup with Hyderabad Python User Group: https://meetu.ps/e/LSCGS/M7kcz/i for the event that you can share with your contacts and community that might be interested to join.

Also, I would like to invite you to follow us on LinkedIn for further updates and news about our group: https://www.linkedin.com/company/hyderabad-python-users-group/.

Thank you @heyswati06 for your time and consideration.
