### ISSUE TITLE
Talk : A deep dive into immudb with Python

### ISSUE THREAD

**Issue by kamahmad** [HydPy/HydPy-meetups#44]
**Title of the talk/workshop**

A deep dive into immudb with Python

**Abstract of the talk/workshop**

immudb is an open-source immutable database that is fast becoming the de-facto way to store immutable data. My talk will include the following - 
- A brief introduction to immutable databases
- How immutable databases differ from Blockchain
- immudb, an open-source immutable db
- immudb under the hood
- Using immudb with Python

**Category of the talk/workshop**

Web development (Databases)

**Duration (including Q&A)**

30 mins (virtual, if possible)

**Level of Audience**

Begineer (Basic understanding of databases)

**Speaker Bio**

- Software Engineer @ Github (Microsoft)
- AWS Certified Solutions Architect
- 9+ years of experience as a backend developer, mostly Python

**Prerequisites(if any)**

None

**Comment by bpkapkar** [comment]
Thank you @kamahmad  for submitting your proposal. We have thoroughly reviewed the proposal and after careful consideration, we have decided to proceed with your proposal and look forward to discussing the next steps.

The upcoming HydPy meet-up is an offline meet-up in Hyderabad. Please let us know your availability for this talk on February 25, 2023, so we can plan further steps accordingly. The talk will last approximately 45 minutes, including a Q&A session. @inovizz

**Comment by kamahmad** [comment]
Thanks a lot @bpkapkar @inovizz I will be available on the 25th of February in Hyderabad. Can you please share the schedule with me.

**Comment by bpkapkar** [comment]
Thanks @kamahmad  for confirmation, we will communicate further steps accordingly.

**Comment by bpkapkar** [comment]
We are writing to request for brief summary about a you and have a photo of you to share with audience attending the talk. Would it be possible for you to provide requested information and allowing to use the same. Thank you for your time and consideration. We look forward to hearing back from you soon.

**Comment by kamahmad** [comment]
Sure, I'm attaching my bio and pic below. Thanks for the opportunity @bpkapkar @inovizz 

> I'm a software engineer at Github (Microsoft) and have been building software for almost a decade. I've worked with many languages but love Python and Go. My current area of interest is system design. 
When I'm not working, I'm reading a book, going on a long drive or spending time with my family. 


<img width="302" alt="image" src="https://user-images.githubusercontent.com/60498143/217993473-720e7504-2416-4fdf-84f4-44ce2114d743.png">

**Comment by bpkapkar** [comment]
I wanted to reach out to you to kindly request that you submit the speaker’s consent form for our upcoming talks. The form can be found at https://forms.gle/xK2CtTcrpUAoNU2YA .

It’s great to have you as a speaker at our event, and your participation would be greatly appreciated. If you have any questions or concerns, please don't hesitate to contact us.

Check out this Meetup with Hyderabad Python User Group: https://meetu.ps/e/LSCGS/M7kcz/i for the event that you can share with your contacts and community that might be interested to join.

Also, I would like to invite you to follow us on LinkedIn for further updates and news about our group: https://www.linkedin.com/company/hyderabad-python-users-group/.

Thank you @kamahmad for your time and consideration.

**Comment by bpkapkar** [comment]
Hello @kamahmad ,
Requesting you to kindly fill the form, we are waiting for the details. Once filled please do confirm, so we can start sharing further meetup details with you.
Thank you.

**Comment by bpkapkar** [comment]
Hello @kamahmad 
Reminder..!!!!
Requesting you to kindly fill the form, we are waiting for the details. Once filled please do confirm, so we can start sharing further talks details with you.
Thank you.

**Comment by kamahmad** [comment]
@bpkapkar sorry I missed the earlier messages. I've filled in the form now. Thank you.

**Comment by bpkapkar** [comment]
@kamahmad Thanks for the confirmation. Will let you know further details.
