### ISSUE TITLE
Manual Tester to Developer Relations - Skills Required to Get into DevRel

### ISSUE THREAD

**Issue by techmaharaj** [HydPy/HydPy-meetups#46]
**Title of the talk/workshop**
Manual Testing to Developer Relations - Skills Required to Get into DevRel

**Abstract of the talk/workshop**
The talk is aimed at anyone who is looking to move into the field of developer relations. In the talk, I'll share about my experience of starting my career as a manual tester, changing roles, and then moving to a developer advocacy role. I'll also explain what a day in the life of a DevRel looks like, and what type of work we do, and also share tips and skills that are required to get into the field of DevRel. Talk about the various roles that are part of the DevRel umbrella, a small JD of each of these roles, and how to find DevRel jobs.

**Category of the talk/workshop**
3. Culture & Society

**Duration (including Q&A)**
30 mins

**Level of Audience**
Beginner - anyone

**Speaker Bio**

With over 8 years of experience in the IT industry, I have worked across various roles and domains. From being a manual tester to heading the innovation lab at one of India's Fortune 500 companies, I've been there and done that. In my current role as a Developer Advocate at InfraCloud, I'm focused on improving the developer onboarding experience for our various cloud-native open-source projects. I'm also an open-source contributor to various projects and a maintainer for Paralus. From creating developer documentation, blog posts, and videos, I love helping people adopt newer technologies and help improve our products.

**Prerequisites(if any)**

**Comment by kalyan678** [comment]
Hi @techmaharaj - As discussed, please modify the talk accordingly and we look forward to see your talk on 16th March!

**Comment by techmaharaj** [comment]
Title: Coding My Way to Community - From Manual Testing to Developer Relations

Ever wondered how your passions outside of work can pivot your career into new, exciting directions? In this talk, I’ll unveil how my journey from manual testing to developer relations was remarkably influenced by my personal blog. I’ll share insights into my introduction to the world of open source, how Python became my tool of choice for crafting demos, and the profound impact of engaging with tech communities.  I'll also explain what a day in the life of a DevRel looks like, and what type of work we do, and also share tips and skills that are required to get into the field of DevRel. Through my story, we'll explore the unexpected ways your interests can align you with your dream job, and will also debunk myths about developer relations.

**Comment by kalyan678** [comment]
> Title: Coding My Way to Community - From Manual Testing to Developer Relations
> 
> Ever wondered how your passions outside of work can pivot your career into new, exciting directions? In this talk, I’ll unveil how my journey from manual testing to developer relations was remarkably influenced by my personal blog. I’ll share insights into my introduction to the world of open source, how Python became my tool of choice for crafting demos, and the profound impact of engaging with tech communities. I'll also explain what a day in the life of a DevRel looks like, and what type of work we do, and also share tips and skills that are required to get into the field of DevRel. Through my story, we'll explore the unexpected ways your interests can align you with your dream job, and will also debunk myths about developer relations.
> 
> Author Bio: Manual tester turned developer advocate. I talk about Cloud Native, Kubernetes & DevOps to help others adopt cloud native. I also create content – blog posts, and webinars – and strongly believe in collaborative learning and growth.
> 
> In addition, I'm also a CNCF Ambassador and the organizer of CNCF Hyderabad. When I am not working, I’m a food & travel blogger & love exploring eateries & going on road trips. You can find me at @TheTechMaharaj on Twitter.
> 
> Photo: https://raw.githubusercontent.com/cncf/people/main/images/atulpriya-sharma.jpg
> 
> @kalyan678 I hope this is fine. Let me know WDYT.

@techmaharaj Looks good. Looking forward to your talk!

**Comment by bpkapkar** [comment]
It was great having you as a speaker @techmaharaj , and we hope to see you at our upcoming meetups. The topic was already presented in the March meetup, so we are ready to close this issue.
