### ISSUE TITLE
Datafication of Indian judicial texts using Natural Language Processing: An Experiment using OpenNyAI on POCSO Cases

### ISSUE THREAD

**Issue by d-saikrishna** [HydPy/HydPy-meetups#49]
**Title of the talk/workshop**

Datafication of Indian judicial texts using Natual Language Processing: An Experiment using [OpenNyAI](https://github.com/OpenNyAI/Opennyai) on POCSO Cases

**Abstract of the talk/workshop**

OpenNyAI is an open-source Python library used to perform NLP operations on Indian legal texts. Named Entity Recognition (NER) and Extractive Summarizer are two NLP models developed under OpenNyAI so far. In this experiment, I discuss the use of OpenNyAI on **POCSO (Protection of Children from Sexual Offences Act)** court judgements in developing structured datasets from judicial texts. I also discuss how OpenNyAI-generated datasets enrich the official metadata made available by the government, thereby helping legal researchers perform quantitative legal research. I end the talk with a few issues I found in the OpenNyAI library, how it could be deployed by the Government and other Public policy questions.

**Category of the talk/workshop**

Data Science, Machine Learning, and AI

**Duration (including Q&A)**

1 hour

**Level of Audience**

Intermediate

**Speaker Bio**

1. I'm Sai Krishna Dammalapati, a Data Engineer at CivicDataLab and a graduate of the National Institute of Technology Karnataka (NITK 2017). Ever since graduation, I've taken an immense interest to work in the intersection of technology (Data Science) and public policy. Over the last 5 years, I worked with NGOs, Universities, Governments and Startups in deploying Data Science solutions to the Public policy problems like Disaster Management, Urbanisation and Air Pollution.
2. Data Engineer at CivicDataLab / B.Tech, National Institute of Technology Karnataka.
3. saikrishnadammalapati@gmail.com
4. Years of experience: 5

**Prerequisites(if any)**

NA. Just a basic understanding of Python is sufficient. My talk will be on first principles.

**Comment by bpkapkar** [comment]
Thank you @d-saikrishna  for submitting your proposal. We have thoroughly reviewed the proposal and after careful consideration, we have decided to proceed with your proposal and look forward to discussing the next steps.

The upcoming HydPy meet-up is an offline meet-up in Hyderabad. Please let us know your availability for this talk on April 1, 2023, so we can plan further steps accordingly. The talk will last approximately 45 minutes, including a Q&A session.

**Comment by d-saikrishna** [comment]
@bpkapkar Hi I’ll be available on April 1st Friday, preferably on the evening. Thank you!

**Comment by inovizz** [comment]
> @bpkapkar Hi I’ll be available on April 1st Friday, preferably on the evening. Thank you!

April 1st is Saturday. Do you think morning hours would work?

**Comment by d-saikrishna** [comment]
@bpkapkar Would be a little struggle due to some other commitment. But yes, I will manage if that’s the only option. Atleast post lunch preferably?

**Comment by bpkapkar** [comment]
@d-saikrishna I am writing to inform you that we have rescheduled our meetup from 1st April to 6th May. I wanted to confirm your availability for the new meetup date, which will be held on 6th May at Hyderabad. Please let me know if this new schedule works for you.

**Comment by d-saikrishna** [comment]
@bpkapkar 6th May? I’ll be out of station in the first week of May. I’ll be back only on 7th May

**Comment by bpkapkar** [comment]
@d-saikrishna I am writing to inform you that we have rescheduled our meetup from 6th May from 13th May. I wanted to confirm your availability for the new meetup date, which will be held on 13th May at Hyderabad. Please let me know if this new schedule works for you.

**Comment by d-saikrishna** [comment]
Hi, yes i will be available on 13th MaySent from my iPhoneOn 29-Apr-2023, at 3:46 PM, Bhushan Kapkar ***@***.***> wrote:﻿
@d-saikrishna I am writing to inform you that we have rescheduled our meetup from 6th May from 13th May. I wanted to confirm your availability for the new meetup date, which will be held on 13th May at Hyderabad. Please let me know if this new schedule works for you.

**Comment by bpkapkar** [comment]
We are writing to request for brief summary about a you @d-saikrishna  and have a photo of you to share with audience attending the talk. Would it be possible for you to provide requested information and allowing to use the same. Thank you for your time and consideration. We look forward to hearing back from you soon.

**Comment by d-saikrishna** [comment]
Sai Krishna is a civic-technologist working to use technology for socio-economic good. His current interests are in building Data Science and Remote Sensing solutions for enabling research work in Child Rights, Disaster Management and Climate Science. Outside of work, Krishna explores writing and theatre for creative expression. Sent from my iPhoneOn 30-Apr-2023, at 2:34 PM, Bhushan Kapkar ***@***.***> wrote:﻿
We are writing to request for brief summary about a you @d-saikrishna  and have a photo of you to share with audience attending the talk. Would it be possible for you to provide requested information and allowing to use the same. Thank you for your time and consideration. We look forward to hearing back from you soon.

**Comment by bpkapkar** [comment]
@d-saikrishna  Thanks for sharing your brief summary. I am unable to see the photo, Will need a photo of you to share with audience attending the talk. Would it be possible for you to provide that.

**Comment by d-saikrishna** [comment]
I’m attaching it again. I’m on travel do doing it via phone. If you cannot download the image, please provide an alternate way to share image. Thank you On 30-Apr-2023, at 6:58 PM, Bhushan Kapkar ***@***.***> wrote:﻿
@d-saikrishna  Thanks for sharing your brief summary. I am unable to see the photo, Will need a photo of you to share with audience attending the talk. Would it be possible for you to provide that.

**Comment by d-saikrishna** [comment]
﻿I’m attaching it again. I’m on travel do doing it via phone. If you cannot download the image, please provide an alternate way to share image. Thank you On 30-Apr-2023, at 6:58 PM, Bhushan Kapkar ***@***.***> wrote:﻿
@d-saikrishna  Thanks for sharing your brief summary. I am unable to see the photo, Will need a photo of you to share with audience attending the talk. Would it be possible for you to provide that.

**Comment by d-saikrishna** [comment]
Sent image on Telegram
