### ISSUE TITLE
High Availability in PostgreSQL with Performance enhancement using Python Code

### ISSUE THREAD

**Issue by John-Solomon** [HydPy/HydPy-meetups#5]
**Title of the talk**
High Availability in PostgreSQL with Performance enhancement using Python Code

**Abstract of the talk**
High availability refers to systems that are durable and likely to operate continuously without failure for a long time.  Of late, businesses want their applications and databases to be up and running without downtime to meet their customer’s demands. They spin up new read replicas during peak seasons to serve the surge in connection traffic. Lot of means and mechanisms are now available. However, when creating new read replicas or slaves, their caches are not warmed to the optimal level when it is newly brought up. So the traffic directed to this node suffers performance degradation.  This python code, fetches the content from the Read Replica no.1 or Slave no.1 and warms the second or other newly spinned up slaves. 

**Duration (including Q&A)**
45 mins to 1 hour

**Level of Audience**
Intermediate/Advanced

**Speaker Bio**
1. Speaker Bio
John is an Associate Consultant with AWS ProServe India, working closely with customers who are migrating from on-prem to the AWS Cloud. He is an AWS certified speaker and speaks at various meetups, breakout sessions, webinars, etc. He is an ardent member of the PostgreSQL community and works as a database administrator for PostgreSQL databases.

2. Company - AWS ProServe India LLP
3. Email - johnsollie1@gmail.com
4. Years of Exp - 21 years

**Comment by inovizz** [comment]
@John-Solomon - would you be able to share the slides and demo code(if it is not proprietary). We'll share that with the meetup audience.
