### ISSUE TITLE
15 year old data scientist as a speaker

### ISSUE THREAD

**Issue by gauravlahoti80** [HydPy/HydPy-meetups#51]
**Title of the talk/workshop**
Understand Algorithmic trading by a 15 year old data scientist working in a Algo Trading platform.

**Abstract of the talk/workshop**
How can we do Algo trading, more about AI and ML. Something about finance and money management. 

**Category of the talk/workshop**
Finance and Technology (FinTech)

**Duration (including Q&A)**
30 minutes 

**Level of Audience**
Intermidiate

**Speaker Bio**
Please do include the following things
1. Gaurav Lahoti is a Data Scientist and was a Full-Stack developer intern with more than a year of experience in development and testing activities. Experience in analyzing and manipulation of data in Python and storing the data in sqlalchemy database. Extensive experience in frontend technologies like ReactJs, HTML and CSS. Vast experience in backend development like processing of data in CSV files provided by the servers and API. Backend also includes Django development, working with URL and URL patterns. Worked as a developer for backtesting systems of Cryptocurrency and even Commodities. Also worked upon the UI of crypto-trading platform. Primarily working on garnering the data from crypto exchanges such as binance, then processing of data, cleaning of data, manipulation of data, getting insights from the data.
2. YXIOM Technologies Pvt Ltd.
3. gauravlahotigl@gmail.com
4. 1+ year of experience

**Prerequisites(if any)**
Nothing specific 

My LinkedIn - 
https://www.linkedin.com/in/gaurav-lahoti-493582201

**Comment by bpkapkar** [comment]
Hello @gauravlahoti80 ,

Thank you for submitting your talk proposal. As this is an old submission, we are closing this request. If you're still interested in giving an in-person talk in Hyderabad, feel free to reopen this request or submit a new one. We'll gladly review the details and consider it for our upcoming meetups.

Thank you for your understanding, and we look forward to your continued interest!
