### ISSUE TITLE
Getting Started with asyncio

### ISSUE THREAD

**Issue by tankala** [HydPy/HydPy-meetups#54]
**Title of the talk/workshop**
Getting Started with asyncio

**Abstract of the talk/workshop**
By default, Python codes are run synchronously. Asynchronous programming makes great sense for I/O-bound tasks like hitting HTTP requests, etc. We can do that using threads but it is too much hassle instead if we get a good understanding asyncio we can do these tasks in a breeze.

**Category of the talk/workshop**
Core Python, Web development

**Duration (including Q&A)**
30 MINS

**Level of Audience**
Beginner

**Speaker Bio**
1. My name is Ashok. I am the founder of piptrends.com. I am a Freelance CTO/Tech Advisor and Leadership and Executive Coach. I have 16+ years of experience in the software industry. I love coding and teaching.
2. Bavanti Software Solutions
3. ashok@bavanti.com
4. 16 years of experience.

**Prerequisites(if any)**
NA. Just a basic understanding of Python is sufficient.

**Comment by INF800** [comment]
+1 for https://www.python-httpx.org/

**Comment by kalyan678** [comment]
This topic was presented in Feb meetup and we are good to close this issue.
