### ISSUE TITLE
Large Language Models 101--- The Beginning of LLMs or End of NLP?

### ISSUE THREAD

**Issue by muhammadyahiya** [HydPy/HydPy-meetups#56]
**Title of the talk/workshop**
Large Language Models 101--- The Beginning of LLMs or End of NLP? 

**Abstract of the talk/workshop**
LLM's are evolving much faster than we stated understand them. It become very much confusion where to start learning and implementation of LLM's. Also there's a wide of knowledge in learner's about NLP, LLM's in detail. Feq questions will try to make answerable with the talk, How LLm's Advancement helping NLP, 
, how NLP Increasingly focused on external, solving real world problems.

**Category of the talk/workshop**
NLP & LLM's 

**Duration (including Q&A)**
(30 mins) 

**Level of Audience**
 Beginner/Intermediate/ 

**Speaker Bio**
**Name : MOHAMMAD YAHIYA**

With over 5 years of dedicated expertise in the dynamic field of data engineering, Yahiya stands at the forefront of innovation, seamlessly integrating technology to solve real-world challenges. As a passionate contributor to the AI community, he have actively engaged with  platforms like Coursera, deeplearning.ai, Workera, Omdena, and Fruitpunch.ai.

**Technical  and Community Builder:**

Yahiya's journey is marked by a robust technical foundation, honed through hands-on experience and continuous learning. He have been an integral part of various AI communities, fostering collaboration and knowledge exchange. This commitment to community is reflected in his association with esteemed organizations like Omdena, where he have curated more than 20 impactful projects in the last 3 years.

**Projects Shaping Human Development:**

A visionary in leveraging AI for human betterment, Yahiya has curated projects that resonate with societal needs. From pioneering habit-building initiatives to developing soft skills recommendation engines, his work extends to critical domains such as AI for road safety and mock interview preparation. Each project serves as a testament to his commitment to driving positive change through technology.

**Founder of OptimumAI Labs**

Elevating his commitment to innovation, Yahiya has recently embarked on a new chapter as the founder of OptimumAI Labs. This AI-based startup is his brainchild, dedicated to pushing the boundaries of what's possible in the realm of artificial intelligence.

**Key Achievements:**
- Over 5 years of hands-on experience in data engineering.
- Active participant and contributor to AI communities on Coursera, deeplearning.ai, Workera, Omdena, and Fruitpunch.ai.
- Curated more than 20 impactful projects in the last 3 years, with a focus on human development.
- Founder of OptimumAI Labs, a startup at the forefront of AI innovation.

**Recent Engagements:**
- Mock Interview prep Chatbot using LLM's where 500+ collaborators registered and build the project in 6 weeks.
Connect with me :
- https://www.linkedin.com/in/shaik-muhammad-yahiya/
- https://github.com/muhammadyahiya

---

Feel free to customize it further based on your needs and additional details.
2. Company/College- Accion Labs
3. Email- yahyasfield@gmail.com
4. Years of Exp -5 years
 -->

**Prerequisites(if any)**

**Comment by muhammadyahiya** [comment]
Updated the talk details

**Comment by muhammadyahiya** [comment]
@bpkapkar  please check the updated session details

**Comment by bpkapkar** [comment]
Thank you so much for expressing interest in speaking at the HydPy meetup. Your proposal looks promising!
Would you be able to give this talk on March 16th in Hyderabad , in person?

**Comment by muhammadyahiya** [comment]
Yes sure, Will be available for the talk @bpkapkar

**Comment by bpkapkar** [comment]
It was great having you as a speaker @muhammadyahiya and we hope to see you at our upcoming meetups. The topic was already presented in the March meetup, so we are ready to close this issue.
