### ISSUE TITLE
Gen AI : Transforming Business Strategies and Customer Interactions

### ISSUE THREAD

**Issue by mithelesh268** [HydPy/HydPy-meetups#60]
Idea for this talk to present how new age AI is going to impact workflows, customer interactions , business strategies. 
The LLMs innovation is not just hype at the this needs to be plugged at the right right place with right tuning. 

Content highlights:
- background
- Whats current situation [current Business & new AI innovation ] 
- How & where AI can be plugged
- Why Python is winning the game
- some demo with liv example
- Conclude , Q&A

**Comment by bpkapkar** [comment]
It was great having you as a speaker @mithelesh268 , and we hope to see you at our upcoming meetups. The topic was already covered in the March meetup, so we are ready to close this issue.
