### ISSUE TITLE
Sharding Using Postgres FDW and Declarative Partitioning

### ISSUE THREAD

**Issue by satyaharish** [HydPy/HydPy-meetups#61]
**Title of the talk/workshop**
Sharding Using Postgres FDW and Declarative Partitioning

**Abstract of the talk/workshop**
1. When to shard. Tuning Postgres before implementing sharding (eg: Indexing, Partitioning, How to analyze query plan)
2. pg extensions comparison - DBLink, FDW, Citus
3. Declarative Partitioning
4. Sharding with postgres_fdw
5. Handling migrations in Django

**Category of the talk/workshop**
Others

**Duration (including Q&A)**
25 mins

**Level of Audience**
Beginner/Intermediate

**Speaker Bio**
1. Speaker Bio (Brief)
	- Ajay Reddy Kanduru is a software engineer who worked with various technologies including Database Architecture, Python, Django, Celery, OAuth, Data Structures, and Algorithms.
Looking forward to sharing knowledge and having discussions with others regarding Sharding strategies. 
2. Company/College
	- Gridlex Services Pvt Ltd
3. Email
	- ajay45177@gmail.com
4. Years of Exp
	- 2 years

**Prerequisites(if any)**
Not Required

**Comment by bpkapkar** [comment]
It was great having you as a speaker @satyaharish, and we hope to see you at our upcoming meetups. The topic was already presented in the April meetup, so we are ready to close this issue.
