### ISSUE TITLE
Exploring GraphQL with Django

### ISSUE THREAD

**Issue by bhansa** [HydPy/HydPy-meetups#62]
**Title of the talk/workshop**
Exploring GraphQL with Django

**Abstract of the talk/workshop**
1. Overview of a  django project and using graphql
2. Understanding different parts of graphql 
3. Using graphiql web editor to form queries
4. Implement graph mutations
5.  [Extra] Use graphql endpoints.

**Category of the talk/workshop**
Web development - Web, Apis, Microservices

**Duration (including Q&A)**
25

**Level of Audience**
Begineer/Internediate/Advance

**Speaker Bio**
1. Speaker Bio (Brief)
  - Bharat is working as a Frontend Lead at Deloitte, having close to 7 years of experience. He has worked with various frontend heavy projects and currently managing a team of 6+ developers. His interests lies in understanding current technology trends, volunteering and contributing to open source. He is currently exploring LLMs and image generation models.

2. Company/College
    - Deloitte
3. Email
   - bsaraswat45@gmail.com
4. Years of Exp
   - close to 7 years of experience

**Prerequisites(if any)**
Good to have pre install django, django-admin and graphene. 
Repository will be shared to follow along.

**Comment by bhansa** [comment]
Slides here: https://www.canva.com/design/DAGCTY2sM0g/eMBJ9KyAElwEqfJT5BV9VQ/view#14

**Comment by bpkapkar** [comment]
It was great having you as a speaker @bhansa  and we hope to see you at our upcoming meetups. The topic was already presented in the April meetup, so we are ready to close this issue.
