### ISSUE TITLE
AI Agents: How to operationalise them at scale?

### ISSUE THREAD

**Issue by SupervityAI** [HydPy/HydPy-meetups#64]
Hi, while most of you are familiar with AutoGen and other agentic frameworks around multi agent systems (MAS) - the real world comes with series of challenges to productionize them in an enterprise/business.

Having built and deployed various AI agents for last few years previously using NLP and now with Gen AI based approach - I will share my real world experience and successful use cases for MAS. Also will discuss about mystery vitamin “R” which is most differentiating in crowded and fast evolving Gen AI toolsets in a business context. 

This is less about tech and more about business dimensions of AI. I’m not delving deep into MAS and architecture but will cover it to what it takes build AI agents at scale for a business.

**Comment by SupervityAI** [comment]
Here are the topics covered in the session:

1. What are AI Agents?
2. ⁠Why businesses need them today?
3. ⁠Successful AI Agent Use Cases in production 
4. ⁠Agentic frameworks and emerging trends
5. ⁠Major challenges faced by AI teams and a practical framework to deploy Gen AI solutions

**Comment by bpkapkar** [comment]
It was great having you as a speaker @SupervityAI  and we hope to see you at our upcoming meetups. The topic was already presented in the May meetup, so we are ready to close this issue.
