### ISSUE TITLE
Putting together Function Calling and RAGs with Gemini

### ISSUE THREAD

**Issue by xprilion** [HydPy/HydPy-meetups#65]
**Title of the talk/workshop**
Putting together Function Calling and RAGs with Gemini

**Abstract of the talk/workshop**
In this hands on session I will walk the audience through understanding Function Calling with Gemini along with how to use RAGs to complement accurately generated answers from Gemini APIs.

Will be starting with this codelab - https://codelabs.developers.google.com/codelabs/gemini-function-calling.
And follow this repo for minimal conceptual understanding of RAGs - https://github.com/xprilion/pure-python-rag-with-in-memory-vector-db

**Category of the talk/workshop**
Data Science, Machine Learning, and AI

**Duration (including Q&A)**
90 mins, QA will go along with the session and rest offline

**Level of Audience**
Beginner to Intermediate

**Speaker Bio**
1. Speaker Bio: A seasoned developer since the pre-Bootstrap era, Anubhav has extensive experience as a freelancer and AI startup founder. He authored "Hands-on Python Deep Learning for Web" and "Mobile Deep Learning with TensorFlow Lite, ML Kit, and Flutter." A Google Developer Expert in Machine Learning and GCP, he was a co-organizer for GDG Cloud Kolkata and TFUG Kolkata communities. Anubhav is often found discussing System Architecture, Machine Learning, and Web technologies.
2. Company: Callchimp.ai
3. Email: xprilion@gmail.com
4. Years of exp: 4

**Prerequisites(if any)**
1. Google Chrome
2. A Google Account
3. Code Editor with Python support (Optional, can follow along on Colab)

**Comment by kalyan678** [comment]
@bhansa - Checkout this details and create flyer accordingly. You can use their SM's to grab the picture :)

**Comment by bpkapkar** [comment]
It was great having you as a speaker @xprilion, and we hope to see you at our upcoming meetups. The topic was already presented in the May meetup, so we are ready to close this issue.
