### ISSUE TITLE
The Guide to Building Open Indic LLMs Today

### ISSUE THREAD

**Issue by ramsrigouthamg** [HydPy/HydPy-meetups#66]
**Title of the talk/workshop**
The Guide to Building Open Indic LLMs Today

**Abstract of the talk/workshop**

- Steps in training modern LLMs
- Challenges specific to Indic Models (Tokenizer + Instruction and Evaluation Datasets)
- Steps in training an Indic LLM
- Techniques that make this possible today on single consumer grade GPU (Quantization, LORA etc)
- Frameworks that further enable speed of training (Unsloth etc)
- Best LLMs suited for Fine-tuning Indic LLMs (Meta Llama 2/3, Google’s Gemma etc)
- How we trained Navarasa 2.0 catering to 15 Indian Languages based on Google’s Gemma.
- Where do we need to make progress? (Regional Datasets for SFT and evaluation, Fine Tuning techniques like ORPO)
- Evolving training techniques (DORA etc)

**Category of the talk/workshop**
Data Science, Machine Learning, and AI

**Duration (including Q&A)**
45 mins

**Level of Audience**
Beginner/Intermediate

**Speaker Bio**
Ramsri is an open-source developer of Indic finetuned LLMs as well as builder of AI SaaS apps (Questgen.ai and Supermeme.ai) from idea to 600k+ users. 
Email: ramsri@questgen.ai
Years of Experience: 11 yrs

**Prerequisites(if any)**
Basic knowledge of AI and ML

**Comment by kalyan678** [comment]
@bhansa - Checkout this details and create flyer accordingly. You can use their SM's to grab the picture :)

**Comment by bpkapkar** [comment]
It was great having you as a speaker @ramsrigouthamg  and we hope to see you at our upcoming meetups. The topic was already presented in the May meetup, so we are ready to close this issue.
