### ISSUE TITLE
Infrastructure as Code (IaC) using Python

### ISSUE THREAD

**Issue by sudhirsingh-cloudbuilders** [HydPy/HydPy-meetups#67]
**Title of the talk/workshop**
Infrastructure as Code (IaC) using Python

**Abstract of the talk/workshop**
Imagine a project where you write the code and give it to operations and when they run the code it creates (or updates) the infrastructure required and then deploys the application in that infrastructure. 
This is possible using infrastructure as code in the programming language of your choice like Python. Along with business functionality you can also write code which creates infrastructure, and then deploys application into that infra.
There is no need to prepare infrastructure specifications and provisioning of infrastructure. Code handles it. 
There are IaC tools like Pulumi, AWS CDK, which have python SDK for IaC.

In this presentation I would like to cover
1.⁠ ⁠What is IaC
2.⁠ ⁠Why IaC (Benefits of IaC)
3.⁠ ⁠A demo of Pulumi python code to create a simple API and Web Application

**Category of the talk/workshop**
DevOps / IaC

**Duration (including Q&A)**
1 hour 15 minutes

**Level of Audience**
Intermediate and Advance

**Speaker Bio**
**Abour Me:** Hi, I'm Sudhir Singh, a seasoned Cloud & DevOps expert with a passion for driving digital transformation for businesses. As a CEO & Co-Founder of CloudBuilders.io, I specialize in helping organizations adopt the cloud the right way - Secure, Resilient, Scalable, Cost-Effective, and with automation at the forefront.

I have extensive experience, designing cloud-native architecture, implementing serverless and event-driven solutions, and delivering high-value business outcomes using AWS, Azure, and GCP. My expertise in DevOps enables me to help software development teams become more agile, productive, and efficient, enabling them to deliver results faster.

With a proven track record of success, I have helped multiple startups design and build their cloud-native products and set up their cloud operations from scratch. I have also assisted customers in building their data ingestion pipelines and creating a 360-degree view of their data, enabling them to make informed business decisions.

**Company**: CloudBuilders Technologies Private Limited (https://cloudbuilders.io)

**Email**: sudhirs@cloudbuilders.io

**Experience**: 22+ years

**Prerequisites(if any)**
If you want to try along Having following would be 
1. Python installed on your laptop 
2. AWS cloud account would be needed.

**Comment by kalyan678** [comment]
Hi @sudhirsingh-cloudbuilders - Thanks for submitting the proposal. We are happy to host you on our June 15th meetup.
@bpkapkar - Please coordinate with Sudhir for collecting his picture in order to create flyer.

**Comment by bpkapkar** [comment]
It was great having you as a speaker @sudhirsingh-cloudbuilders  and we hope to see you at our upcoming meetups. The topic was already presented in the June meetup, so we are ready to close this issue.
