### ISSUE TITLE
Embedding and fine tunning of AI copilot

### ISSUE THREAD

**Issue by algsks** [HydPy/HydPy-meetups#73]
**Title of the talk/workshop**

**Abstract of the talk/workshop**
Embedding improves the copilot's understanding of the code's meaning by converting text into numerical representations (embeddings). This allows the copilot to find relevant information and context within the codebase.

Fine-tuning involves further training a pre-trained AI model on a specific dataset related to the desired programming domain. This customizes the copilot's responses to better address the programmer's needs within that domain.

**Category of the talk/workshop**
Software Engineering or Artificial Intelligence

**Duration (including Q&A)**
45 min

**Level of Audience**
any

**Speaker Bio**
1. Speaker Bio:Worked on real-time data handling from different sources like (SFTP, Local Servers) and onboard data using Azure Data Factory, Event Hub, and stream analytics job. Deploy resources (Data Factory, Data Bricks, Data Lake, Synapse, Stream analytics, Event hub, Managed instance) and manage them as per project requirement.
Handle server on the Azure platform and schedule jobs and pipeline as per project requirement. 
Making PowerBI Report and managing data validation.
Working as AD administrator and security contributor on the Azure platform.
providing training on azure, Power bi, Power Platform,Power APP,python, algo, dev-ops and also work as freelancer azure consultant
2. Company/College: neudesic technologies pvt. ltd
3. Email: algskskj@gmail.com
4. Years of Exp:8+

**Prerequisites(if any)**
internet, projector, electricity

**Comment by bpkapkar** [comment]
It was great having you as a speaker @algsks and we hope to see you at our upcoming meetups. The Another topic from same speaker was already presented in the July meetup, so we are ready to close this issue.
