### ISSUE TITLE
Azure data engineering Using Synapse

### ISSUE THREAD

**Issue by algsks** [HydPy/HydPy-meetups#74]
**Title of the talk/workshop**
Azure data engineering Using Synapse

**Abstract of the talk/workshop**
This workshop is designed to empower students with the skills to harness the power of Azure Synapse Analytics for data engineering tasks. Participants will gain hands-on experience in building robust and scalable data pipelines, utilizing a variety of data sources and formats. The workshop will cover essential concepts such as data ingestion, transformation, and loading, as well as advanced topics like data warehousing, machine learning, and real-time analytics. By the end of the workshop, students will have a solid foundation in Azure Synapse and be equipped to tackle complex data engineering challenges.

**Category of the talk/workshop**
Primary Category:
Data Engineering
Secondary Categories:
Azure and Cloud Computing
Student Development
Technical Workshop
Higher Education

**Duration (including Q&A)**
1 HR

**Level of Audience**
Any but helpful for intermediate

**Speaker Bio**

**Prerequisites(if any)**
Internet, electricity, projector

**Comment by bpkapkar** [comment]
It was great having you as a speaker @algsks  and we hope to see you at our upcoming meetups. The topic was already presented in the July meetup, so we are ready to close this issue.
