### ISSUE TITLE
Data Orchestration using MWAA (Managed Workflows for Apache Airflow)

### ISSUE THREAD

**Issue by ng-bhanu** [HydPy/HydPy-meetups#76]
Amazon Managed Workflows for Apache Airflow (MWAA) simplifies this process by providing a fully managed service for Airflow on the AWS cloud.  With MWAA, you can focus on building your workflows without worrying about the underlying infrastructure.
What You Will Learn:
- The fundamentals of data workflows and Apache Airflow.
- The key features and benefits of MWAA.
- How to get started with MWAA, including setting up an environment and building basic workflows.
- Practical use cases of MWAA for different scenarios.

Category of the talk/workshop
Primary Category: Data Engineering

Duration (including Q&A)
45 mins

Level of Audience
Beginner

Speaker Bio
Bhanu is a Principal Data Engineer at Ngenux Solutions Pvt Ltd
Email: [bhanu.dasari@ngenux.com](mailto:bhanu.dasari@ngenux.com)
Years of Experience: 17 yrs

Prerequisites(if any)
Prior knowledge of Azure Data Engineering

**Comment by bpkapkar** [comment]
It was great having you as a speaker @ng-bhanu  and we hope to see you at our upcoming meetups. The topic was already presented in the July meetup, so we are ready to close this issue.
