### ISSUE TITLE
Building a RAG App with Groq (Llama-3), Hugging Face opensource model and Llama-Index: A Love-Hate Story

### ISSUE THREAD

**Issue by Mohammad-Palla** [HydPy/HydPy-meetups#78]
**Title of the talk/workshop**
Building a RAG App with Groq (Llama-3), Hugging Face opensource model and Llama-Index: A Love-Hate Story

**Abstract of the talk/workshop**
How to build a RAG app with groq (llama-3) and llama-index, Hugging Face without OpenAI API keys and with minimal compute

**Category of the talk/workshop**
Gen AI, RAG apps

**Duration (including Q&A)**
25 mins

**Level of Audience**
Intermediate

**Speaker Bio**

1. Full-Stack Developer | MERN Stack | Generative AI | LLMs and RAG powered apps | Web & Mobile App Development
2. maths.ai
3. mohammadpalla24@gamil.com
4. 1 YOE

**Comment by kalyan678** [comment]
@Mohammad-Palla - Thanks for submitting the proposal. Could you please give us a slight detail outline of your proposal. On an other note, are you available to present talk on 31st Aug in person in Hyderabad?

**Comment by Mohammad-Palla** [comment]
I will be converting the blog that I wrote into a presentation https://blog.palla.co.in/RAG-app-with-groq-and-llama-index-without-OpenAI

Yes I am available on 31st Aug in person

**Comment by kalyan678** [comment]
> I will be converting the blog that I wrote into a presentation https://blog.palla.co.in/RAG-app-with-groq-and-llama-index-without-OpenAI
> 
> Yes I am available on 31st Aug in person

@Mohammad-Palla - LGTM! Yeah start preparing the presentation and  try to cover the things in 30m mins. I believe you will walk through the code during your demo right?
 On an other note, we need your social handle details including picture so that we can create a flyer.

**Comment by Mohammad-Palla** [comment]
Yes I will walk through the code in live demo. hope there is wifi at the venue. Where do I share the details ?

**Comment by kalyan678** [comment]
> Yes I will walk through the code in live demo. hope there is wifi at the venue. Where do I share the details ?

@Mohammad-Palla - You can share it here.

**Comment by Mohammad-Palla** [comment]
twitter: x.com/pallamohammad
linkedin: https://www.linkedin.com/in/mohammad-palla-6017221b8/
personal website: palla.co.in
![me4](https://github.com/user-attachments/assets/fae4e373-7ca9-408a-930a-9e3364f3297a)

**Comment by kalyan678** [comment]
@Mohammad-Palla - Due to some unavoidable situations we have cancelled the Aug month meetup. We will reach out to you again when plan our next meetup. We really appreciate your understanding!

**Comment by bpkapkar** [comment]
@Mohammad-Palla   We are planning a meetup on October 19th and would love to know your availability for an in-person gathering in Hyderabad. This will help us organize the event and accommodate the talk accordingly.

**Comment by bpkapkar** [comment]
@Mohammad-Palla
