### ISSUE TITLE
Data to Actionabe Insights | The Role of Data Literacy

### ISSUE THREAD

**Issue by hemda007** [HydPy/HydPy-meetups#79]
**Title of the talk/workshop**
Data to Actionabe Insights | The Role of Data Literacy

**Abstract of the talk/workshop**
Most companies have a lot of data but they fail to derive actionable insights from it. The major reason is not the lack of tools or talent, it's the lack of data literacy across the organisation. This talk will highlight how successful companies convert data to meaningful insights and the significance of data literacy in achieving the same.

**Category of the talk/workshop**
11. Others

**Duration (including Q&A)**
40 minutes

**Level of Audience**
Intermediate to Advanced

**Speaker Bio**
1. Speaker Bio (Brief)
Hemanand is the Co-Founder of Codebasics which is popular  YT channel and an e-learning platform focussed on data science. He has around 8 years of international experience in data analytics working across different business functions.

2. Company/College
Codebasics
3. Email
hem@codebasics.io
4. Years of Exp
8+

**Prerequisites(if any)**
There will be an interactice quiz during the session for which the audience will need their phone with stable internet. (No need to login with email/phone number to any website. I presume there will be a projector. I can bring my own slide pointer. Thanks for the opportunity.

**Comment by bpkapkar** [comment]
@hemda007  We are planning a meetup on October 19th and would love to know your availability for an in-person gathering in Hyderabad. This will help us organize the event accordingly.

**Comment by bpkapkar** [comment]
It was great having you as a speaker @hemda007 and we hope to see you at our upcoming meetups. The topic was already presented in the December meetup, so we are ready to close this issue.
