### ISSUE TITLE
Getting started with Kaggling

### ISSUE THREAD

**Issue by OmAshish** [HydPy/HydPy-meetups#81]
**Title of the talk/workshop**
Getting started with Kaggling

**Abstract of the talk/workshop**
This would cover:
1. What is Kaggle? (2 Mins)
2. How to start with Kaggling? (3 mins)
3. What are the different components of Kaggle? (5 mins)
4. Best Practices on Kaggle (10 mins)
5. How to become a Master and GrandMaster in Kaggle (3 mins)
6. Whats new with Kaggle AI Learning? (2 mins)
7. QnA (5 mins)

**Category of the talk/workshop**
Its a Talk Event but will be happy to see people following on laptop/mobile device for week remembrance!

**Duration (including Q&A)**
30 mins

**Level of Audience**
Begineer and Intermediate

**Speaker Bio**

Product Data Scientist, Ex- AI Engineer at HSBC, Hitachi, HP with 3+ Years in Industry
IIT Kanpur Alumini, 
Community Speaker, Kaggle Expert, 
6x Azure, 4x GCP Certified,
MIT Innovation BootCamper, Harvard Golden Delegate,
30+ Event Speaker for NGOs and Student Upliftment!

email: Omashish100@gmail.com

**Prerequisites(if any)**
a. If you have any specific requirement from audience
No
b. for the talk i.e. software, tools set up on machine etc, please 
No

**Comment by OmAshish** [comment]
**Title of the talk/workshop**
Fast-Track Your Data with Polars: A Speedy Alternative to Pandas

**Abstract of the talk/workshop**
This would cover:
1. Brief overview of Polars and its origins
2. Key Features and Advantages
3. Hands-On Comparison: Polars vs. Pandas
4. Real Life Applications
5. Learning Material/Links
6. QnA 

**Category of the talk/workshop**
Its a Talk Event!

**Duration (including Q&A)**
30 mins

**Level of Audience**
Begineer and Intermediate

**Speaker Bio**

Product Data Scientist, Ex- AI Engineer at HSBC, Hitachi, HP with 3+ Years in Industry
IIT Kanpur Alumini, 
Community Speaker, Kaggle Expert, 
6x Azure, 4x GCP Certified,
MIT Innovation BootCamper, Harvard Golden Delegate,
30+ Event Speaker for NGOs and Student Upliftment!

email: Omashish100@gmail.com

**Prerequisites(if any)**
a. If you have any specific requirement from audience
No
b. for the talk i.e. software, tools set up on machine etc, please 
No

**Comment by bpkapkar** [comment]
@OmAshish We are planning a meetup on October 19th and would love to know your availability for an in-person gathering in Hyderabad. This will help us organize the event accordingly.

**Comment by bpkapkar** [comment]
It was great having you as a speaker @OmAshish and we hope to see you at our upcoming meetups. The another topic from same speaker was presented in the October meetup, so we are ready to close this issue.
