### ISSUE TITLE
first comment 

### ISSUE THREAD

**Issue by shashankch2003** [HydPy/HydPy-meetups#83]
**Title of the talk/workshop**

**Abstract of the talk/workshop**

**Category of the talk/workshop**

**Duration (including Q&A)**

**Level of Audience**

**Speaker Bio**

**Prerequisites(if any)**

**Comment by bpkapkar** [comment]
@shashankch2003  Upon review, this does not appear the talk proposal. Therefore, I will proceed with closing this issue
