### ISSUE TITLE
Ensuring data quality in web scraping with data contracts

### ISSUE THREAD

**Issue by dayananDchallA** [HydPy/HydPy-meetups#87]
Title of the talk/workshop
Ensuring data quality in web scraping with data contracts

Abstract of the talk/workshop
Web scraping is an important tool for businesses and researchers but there are challenges like messy or incomplete data, and making sure the data follows privacy rules. These issues can make it hard to get valuable insights from the scraped data.

This is where data contracts help. A data contract is a set of rules that define how the data should look and what quality it should have. By using data contracts in web scraping, you can make sure the data is reliable and meets privacy standards. 

Category of the talk/workshop
The session will include hands-on web scraping using data contracts and building an ETL pipeline

Duration (including Q&A)
30 mins

Level of Audience
Intermediate/Advanced

Speaker Bio

Full stack machine Learning Engineer with 12 + years of experience working in different domains. 
Core Skills: Python, Machine Learning, Deep Learning, Gen AI, Computer Vision.
Ngenux
[dayananada.challa@ngenux.com](mailto:dayananada.challa@ngenux.com)
12 + years

Prerequisites(if any)
Python

Alternate Proposal
+++++++++++++++++++++++++
Design Patterns in machine learning

**Comment by bpkapkar** [comment]
Thank you @dayananDchallA  for submitting your proposal! It looks promising, and we’re excited about the possibility of including it in our October 19th meetup. Could you please confirm your availability for in person talk in Hyderabad and also share a photo for the event flyer.

Looking forward to your response! @bhansa

**Comment by bpkapkar** [comment]
It was great having you as a speaker @dayananDchallA  and we hope to see you at our upcoming meetups. The topic was already presented in the October meetup, so we are ready to close this issue.
