### ISSUE TITLE
Understanding Python Decorators

### ISSUE THREAD

**Issue by ashok-piptrends** [HydPy/HydPy-meetups#88]
**Title of the talk/workshop**
Understanding Python Decorators

**Abstract of the talk/workshop**
We use decorators in many places. When we create an API route, dataclass & etc. But how it works few people know. Want to cover through this talk what are they and how we can build our own.
Outline:
1. what exactly is Decorator?
2. Understanding Python Functions as First class citizens Function as an input argument, Function as a Return Value, Inner functions
3. Understanding Decorators with a Simple Example Simple Decorator Example, Adding Syntactic Sugar to it, Problem with this simple Approach, Solving it with @functools.wraps
4. Some Real World Examples Timing Decorator, Passing arguments to the decorator

**Category of the talk/workshop**
Core Python

**Duration (including Q&A)**
30 mins

**Level of Audience**
Beginner

**Speaker Bio**
My name is Ashok Tankala. I am a Fractional CTO. I have 16+ years of experience in the software industry. I am the founder of [piptrends.com](https://piptrends.com/).

**Prerequisites(if any)**
Basic Python Knowledge

**Comment by bpkapkar** [comment]
It was great having you as a speaker @ashok-piptrends and we hope to see you at our upcoming meetups. The topic was already presented in the October meetup, so we are ready to close this issue.
