### ISSUE TITLE
Talk Proposal - Pandas Optimization

### ISSUE THREAD

**Issue by pranalibose** [HydPy/HydPy-meetups#90]
**Title of the talk/workshop**

Pandas Optimization Hacks

**Abstract of the talk/workshop**

Pandas different optimization techniques

**Category of the talk/workshop**

Python Optimization

**Duration (including Q&A)**

30 mins

**Level of Audience**

Intermediate-Advance

**Speaker Bio**

1. Machine Learning Engineer with 7 years of experience working in different domains. Core Skills: Python, Data Manipulation and Visualisation, Data Science and Machine Learning mainly supervised and unsupervised.
2. DBS
3. [pranalibose01@gmail.com](mailto:pranalibose01@gmail.com)
4. 7 years

**Prerequisites(if any)**

**Details**
Intend to cover the below pandas optimization techniques:
1. Memory Optimization
2. Vectorization
3. Chunking Method
4. Filter Optimization
5. Profiling

**Comment by bpkapkar** [comment]
Thank you @pranalibose for submitting your proposal! It looks promising, and we’re excited about the possibility of including it in our October 19th meetup. Could you please confirm your availability for in person talk in Hyderabad and also share a photo for the event flyer.

Looking forward to your response!

**Comment by pranalibose** [comment]
@bpkapkar glad to know! Sure, I am available on 19th but would request to schedule my talk in the beginning of the event because I would need to leave early. Also, can I request a formal invitation so that I can seek permission from my org?

**Comment by bpkapkar** [comment]
Great to hear @pranalibose ! We'll schedule your talk at the beginning of the event. We also send you a formal invitation shortly for your organization’s approval. Kindly share a photo for the event flyer.

Looking forward to see you on 19th October!
