### ISSUE TITLE
Data Science, Machine Learning, and AI

### ISSUE THREAD

**Issue by kumar703** [HydPy/HydPy-meetups#92]
**Title of the talk/workshop**

**Abstract of the talk/workshop**

**Category of the talk/workshop**

**Duration (including Q&A)**

**Level of Audience**

**Speaker Bio**

**Prerequisites(if any)**

**Comment by bpkapkar** [comment]
@kumar703  Upon review, this does not appear the talk proposal. Therefore, I will proceed with closing this issue
