### ISSUE TITLE
Organized Chaos: Demystifying Memory Management & Garbage Collection in Python

### ISSUE THREAD

**Issue by Sejal-G** [HydPy/HydPy-meetups#93]
***Title of the talk/workshop**
Organized Chaos: Demystifying Memory Management & Garbage Collection in Python

**Abstract of the talk/workshop**
Ever wondered what goes on behind the scenes to keep your Python apps running smoothly? Join in for a deep dive into the world of garbage collection and resource allocation! Uncover the secrets of Python's memory management, from reference counting to tackling those pesky cyclic references & how Python automatically identifies and cleans up unused objects, ensuring optimal performance using `gc` module. You'll also get a scoop of techniques like Global Interpreter Lock (GIL) and Generational Garbage Collector. Whether you're a Python pro or just curious, this talk will help you keep your code lean, clean and efficient. Don't miss it!

**Category of the talk/workshop**
4. Core Python - Language Features, Python Implementations, Extending Python and Standard Library, language internals

**Duration (including Q&A)**
25-30 mins

**Level of Audience**
Beginner-Intermediate

**Speaker Bio**

Please bring your curiosity along. That's it. :)

**Comment by Sejal-G** [comment]
Apologies, the Speaker Bio is here:
Sejal Gupta (She/Her) is a software engineer, fueled by a passion for technology and constantly strives to empower women in tech. She founded a community (Women in Tech++) where she has mentored 100+ women and seeks to keep this legacy. She has authored 3 research articles on the Internet of Things and presented her work at IEEE Conferences. She is a public speaker and loves to talk about solving problems using cutting-edge technology. She graduated from the National Institute of Technology, Kurukshetra in 2021. You may contact her via Gmail at sejalnit@gmail.com or [LinkedIn](https://www.linkedin.com/in/sejal-gupta-she-her), [Github](https://github.com/Sejal-G), [Scopus](https://www.scopus.com/authid/detail.uri?authorId=57222596059), [Google Scholar](https://scholar.google.com/citations?hl=en&user=8O4uOVYAAAAJ)

**Comment by bpkapkar** [comment]
It was great having you as a speaker @Sejal-G and we hope to see you at our upcoming meetups. The topic was already presented in the November meetup, so we are ready to close this issue.

**Comment by bpkapkar** [comment]
It was great having you as a speaker @Sejal-G  and we hope to see you at our upcoming meetups. The topic was already presented in the November meetup, so we are ready to close this issue
