### ISSUE TITLE
Beyond Metrics: Evaluating Large Language Models

### ISSUE THREAD

**Issue by VishnuVardhanSaiLanka** [HydPy/HydPy-meetups#94]
Title of the talk/workshop
Beyond Metrics: Evaluating Large Language Models

Abstract of the talk/workshop
In the rapidly advancing world of AI, evaluating Large Language Models (LLMs) is critical to ensure their safety, reliability, and fitness for purpose. This talk explores the evolving landscape of LLM evaluation, going beyond traditional metrics like BLEU and accuracy. We delve into automated benchmarks, human evaluation, and using LLMs as evaluators themselves, highlighting their strengths and limitations. Attendees will gain insights into practical evaluation challenges, overlooked aspects like societal impacts, and the importance of domain-specific metrics. Additionally, the session introduces open-source tools and a comprehensive checklist to streamline evaluation processes for production readiness.

Category of the talk/workshop
Generative AI, Evals

Duration (including Q&A)
30mins

Level of Audience
Beginner

Speaker Bio
Vishnu Vardhan is a Associate Tech Lead at Kore.ai, actively engaged in the field of Generative AI and LLMs. His expertise lies in Machine Learning and NLP, with a growing proficiency in MLOps. Vishnu is committed to crafting AI solutions that are aligned and secure, with a focus on achieving tangible real-world impact.

email: vardhanvishnu691@gmail.com

Prerequisites(if any)
Basic understanding of GenAI

**Comment by bpkapkar** [comment]
It was great having you as a speaker @VishnuVardhanSaiLanka and we hope to see you at our upcoming meetups. The topic was already presented in the December meetup, so we are ready to close this issue.
